[tool.poetry]
name = "cjobs"
version = "0.0.1"
description = ""
authors = ["Attilio Chiavegatti <attiliochiavegatti@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
fire = "^0.5.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
